public class ShiftAttack {
    public static int l= 14;
    public static void main(String[] args) {
        String ciphertext = "GCMKGKRDBYTZLRORMTZLROGFEXIKCORSNSDZHFAZWLNCLIZIMZFWOTIPJIJOBIVQSPYURVTCSKTSNZJCRESEZMMUKZVMVCA" +
                "XHFASTEXCYPAYNHIZIUUHUIMZFUAYPZQSBOAXKCSGRRMMZGRHKEXBFCGGXVJTMUXNFTOLDYYWASPITKKCCSSGRUNCDCURWDRCNZVVGWEIURJ" +
                "DRCORSXDSQATHVXCLOSMTYCATXMEZGCVKVPCILTKVRIRDOXEXZFCVKVPCSPOGRUXCUAXHVQSPYIVVVHMRGRUYSQTXSPZFMFIMMDZGZGXZJBC" +
                "VKVPFWLGGRUKSYSGRKZJCRECFPBECUYGGSGNRSMZSTEXCDJHFEXEEYTYTNIICCNELYCXVGLJMEQSLTUVRIRCXVPFMSPEBIITHCAILVMCDMUV" +
                "RGGCVKVPXCPRATKKCJIZMTDOLEBIITGSPKVJOOPEBIITGSPXIDZZCAJIIZJCREWRDBRATHJDBLEXMEOVCHOWKJFWOLSLMGNEIMVNZGVKHKCS" +
                "PEURRHCREUJUPGRSAWGZBBEJMEVGSNHIRHHFEKEIOVGSGZVMMQMGPCNHYGKMEVJYSZGFNAGCGVVIORHORBJTRHKVZQSPSUJSGCMDYTZGZCDH" +
                "CRGZRHUWVBSLEXECNOLDKQGZFMRYWFOVYTORXGCPYGRUOFGUSTYOVCYISLGRZEISDZHFESSDZBRAXCDVGREXWFAODRGGKDCLOLEUJHRHORBJ" +
                "TRHKIEYZCSYGIPSJTOIJQWQIZIUWMRHKMECOZIZEEOGMFURVXCPNKVFAHFIYTZSSJOTXYZGAAXGVGMBIYXZIUSIYLRWZCITLRWWRATXJJTQO" +
                "SIFOVCRISIISPHUAWMSOUKRKOVCIXQZNILDKVJOOLDORXNVMWKEXZFRHKCRMSROQMCGCLEGRFOVCRNSNASPVKRKOVCIXLROFCDY";
        String x = "GCMKGKRDBYTZLRORMTZLROGFEXIKCORSNSDZHFAZWLNCLIZIMZFWOTIPJIJOBIVQSPYURVTCSKTSNZJC\n" +
                "RESEZMMUKZVMVCAXHFASTEXCYPAYNHIZIUUHUIMZFUAYPZQSBOAXKCSGRRMMZGRHKEXBFCGGXVJTMUXN\n" +
                "FTOLDYYWASPITKKCCSSGRUNCDCURWDRCNZVVGWEIURJDRCORSXDSQATHVXCLOSMTYCATXMEZGCVKVPCI\n" +
                "LTKVRIRDOXEXZFCVKVPCSPOGRUXCUAXHVQSPYIVVVHMRGRUYSQTXSPZFMFIMMDZGZGXZJBCVKVPFWLGG\n" +
                "RUKSYSGRKZJCRECFPBECUYGGSGNRSMZSTEXCDJHFEXEEYTYTNIICCNELYCXVGLJMEQSLTUVRIRCXVPFM\n" +
                "SPEBIITHCAILVMCDMUVRGGCVKVPXCPRATKKCJIZMTDOLEBIITGSPKVJOOPEBIITGSPXIDZZCAJIIZJCR\n" +
                "EWRDBRATHJDBLEXMEOVCHOWKJFWOLSLMGNEIMVNZGVKHKCSPEURRHCREUJUPGRSAWGZBBEJMEVGSNHIR\n" +
                "HHFEKEIOVGSGZVMMQMGPCNHYGKMEVJYSZGFNAGCGVVIORHORBJTRHKVZQSPSUJSGCMDYTZGZCDHCRGZR\n" +
                "HUWVBSLEXECNOLDKQGZFMRYWFOVYTORXGCPYGRUOFGUSTYOVCYISLGRZEISDZHFESSDZBRAXCDVGREXW\n" +
                "FAODRGGKDCLOLEUJHRHORBJTRHKIEYZCSYGIPSJTOIJQWQIZIUWMRHKMECOZIZEEOGMFURVXCPNKVFAH\n" +
                "FIYTZSSJOTXYZGAAXGVGMBIYXZIUSIYLRWZCITLRWWRATXJJTQOSIFOVCRISIISPHUAWMSOUKRKOVCIX\n" +
                "QZNILDKVJOOLDORXNVMWKEXZFRHKCRMSROQMCGCLEGRFOVCRNSNASPVKRKOVCIXLROFCDY";
        System.out.println("direct copy and paste from the homework assignment:");
        possibleKeyLength(x);
        System.out.println("WithoutSpaces:");
        possibleKeyLength(ciphertext);
        System.out.println("Highest Shift: 7,Highest Coincidences:81");

    }
    public static void possibleKeyLength(String cyphertext){


        for(int shift =1 ;shift<=14 ; shift++ ){
            int counter = 0;
            for(int index = 0; index<cyphertext.length();index++){
                int shiftindex = (index+shift)%cyphertext.length();
                if(cyphertext.charAt(index)==cyphertext.charAt(shiftindex)){
                    counter+=1;
                }
            }
            System.out.print("Shift: "+shift+ " ");
            System.out.println("Coincidences: "+counter);
        }
    }
}
